export const LOGIN_SUCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_START = 'LOGIN_START';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const FETCH_MEASUREMENTS_START = 'FETCH_MEASUREMENTS_START';
export const FETCH_MEASUREMENTS_SUCCESS = 'FETCH_MEASUREMENTS_SUCCESS';
export const FETCH_MEASUREMENTS_FAILURE = 'FETCH_MEASUREMENTS_FAILURE';

export const POST_MEASUREMENT_START = 'POST_MEASUREMENT_START';
export const POST_MEASUREMENT_SUCCESS = 'POST_MEASUREMENT_SUCCESS';
export const POST_MEASUREMENT_FAILURE = 'POST_MEASUREMENT_FAILURE';

export const PUT_MEASUREMENT_START = 'PUT_MEASUREMENT_START';
export const PUT_MEASUREMENT_SUCCESS = 'PUT_MEASUREMENT_SUCCESS';
export const PUT_MEASUREMENT_FAILURE = 'PUT_MEASUREMENT_FAILURE';

export const DELETE_MEASUREMENT_START = 'DELETE_MEASUREMENT_START';
export const DELETE_MEASUREMENT_SUCCESS = 'DELETE_MEASUREMENT_SUCCESS';
export const DELETE_MEASUREMENT_FAILURE = 'DELETE_MEASUREMENT_FAILURE';

export const GET_MEASUREMENT_TYPES_START = 'GET_MEASUREMENT_TYPES_START';
export const GET_MEASUREMENT_TYPES_SUCCESS = 'GET_MEASUREMENT_TYPES_SUCCESS';
export const GET_MEASUREMENT_TYPES_FAILURE = 'GET_MEASUREMENT_TYPES_FAILURE';

export const SET_DATE_FILTER = 'SET_DATE_FILTER';
export const SET_PREVIOUS_DATE_FILTER = 'SET_PREVIOUS_DATE_FILTER';
export const SET_NEXT_DATE_FILTER = 'SET_NEXT_DATE_FITLER';
